ARG images_version
ARG base_image
FROM ${base_image} as installer

# version with own MPI lib
# RUN env MPICC=$(cat /.mpiccpath) python3 -m pip install --no-cache-dir --ignore-installed  mpi4py

# version with default MPI lib - currently OpenMPI
# RUN python3 -m pip install --no-cache-dir --ignore-installed  mpi4py
